# Generated by Django 4.1.6 on 2023-02-04 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('types', models.CharField(choices=[('director', 'Director'), ('writer', 'Writer'), ('actor', 'Actor')], max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('poster', models.ImageField(upload_to='movie_poster/%Y/%m/%d/', verbose_name='poster')),
                ('bg_picture', models.ImageField(upload_to='movie_bg_picture/%Y/%m/%d/', verbose_name='bg_picture')),
                ('release_year', models.PositiveIntegerField(verbose_name='release year')),
                ('mpa_rating', models.CharField(choices=[('G', 'G'), ('PG', 'Pg'), ('PG-13', 'Pg13'), ('R', 'R'), ('NC-17', 'Nc17')], max_length=20)),
                ('imdb_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='score')),
                ('duration', models.PositiveIntegerField(verbose_name='duration')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('directors', models.ManyToManyField(related_name='movie_directors', to='ua_imdb.person')),
                ('genre', models.ManyToManyField(blank=True, related_name='genre_movie', to='ua_imdb.genre')),
                ('stars', models.ManyToManyField(related_name='movie_stars', to='ua_imdb.person')),
                ('writers', models.ManyToManyField(related_name='movie_writers', to='ua_imdb.person')),
            ],
        ),
    ]
